### Update an existing patient entity
PUT http://localhost:4000/patients/353e2fc0-18e8-4f60-bba7-09824916b6df
Content-type: application/json

{
  "name" : "Suman Dangol",
  "email" : "suman@example.com",
  "address" : "123 main street",
  "dateOfBirth" : "1991-05-05"
}

###